run:
  deadline: "20s"
  issues-exit-code: 1

linters-settings:
  errcheck:
    check-blank: false

linters:
  enable:
    - revive
    - gochecknoglobals

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude errcheck from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
