name: "CI/Rust"
on:
  workflow_call:

jobs:
  go_lints:
    uses: "boinkor-net/ci-baseline-go/.github/workflows/ci_baseline_go_lints.yml@main"
    with:
      go_version: "1.20"

  go_tests:
    uses: "boinkor-net/ci-baseline-go/.github/workflows/ci_baseline_go_tests.yml@main"
    with:
      go_version: "1.20"


